/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package texteditor;

import java.awt.Color;

/**
 *
 * @author vchin
 */
public class TextEditor extends javax.swing.JDialog {

    /**
     * Creates new form TextEditor
     */
    public TextEditor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        redo = new javax.swing.JButton();
        undo = new javax.swing.JButton();
        resaltar = new javax.swing.JButton();
        guardarcomo = new javax.swing.JButton();
        guardar = new javax.swing.JButton();
        abrir = new javax.swing.JButton();
        crear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        fileTxtA = new javax.swing.JTextArea();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(774, 512));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(null);

        redo.setBackground(new java.awt.Color(255, 255, 255));
        redo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/redo.jpeg"))); // NOI18N
        jPanel1.add(redo);
        redo.setBounds(560, 10, 75, 60);

        undo.setBackground(new java.awt.Color(255, 255, 255));
        undo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/undo.jpeg"))); // NOI18N
        jPanel1.add(undo);
        undo.setBounds(470, 10, 75, 60);

        resaltar.setBackground(new java.awt.Color(255, 255, 255));
        resaltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/highlight.png"))); // NOI18N
        jPanel1.add(resaltar);
        resaltar.setBounds(380, 10, 75, 60);

        guardarcomo.setBackground(new java.awt.Color(255, 255, 255));
        guardarcomo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/saveasfile.png"))); // NOI18N
        jPanel1.add(guardarcomo);
        guardarcomo.setBounds(290, 10, 72, 60);

        guardar.setBackground(new java.awt.Color(255, 255, 255));
        guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/savefile.jpeg"))); // NOI18N
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });
        jPanel1.add(guardar);
        guardar.setBounds(200, 10, 75, 60);

        abrir.setBackground(new java.awt.Color(255, 255, 255));
        abrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/openfile.jpeg"))); // NOI18N
        abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirActionPerformed(evt);
            }
        });
        jPanel1.add(abrir);
        abrir.setBounds(100, 10, 80, 60);

        crear.setBackground(new java.awt.Color(255, 255, 255));
        crear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/newfile.png"))); // NOI18N
        crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearActionPerformed(evt);
            }
        });
        jPanel1.add(crear);
        crear.setBounds(10, 10, 70, 60);

        fileTxtA.setBackground(new java.awt.Color(204, 204, 204));
        fileTxtA.setColumns(20);
        fileTxtA.setRows(5);
        fileTxtA.setEnabled(false);
        jScrollPane1.setViewportView(fileTxtA);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(0, 80, 780, 430);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guardarActionPerformed

    private void crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearActionPerformed
        fileTxtA.setBackground(Color.white);
        fileTxtA.setEnabled(true);
    }//GEN-LAST:event_crearActionPerformed

    private void abrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirActionPerformed
        fileTxtA.setBackground(Color.white);
        fileTxtA.setEnabled(true);
    }//GEN-LAST:event_abrirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TextEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TextEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TextEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TextEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TextEditor dialog = new TextEditor(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton abrir;
    private javax.swing.JButton crear;
    private javax.swing.JTextArea fileTxtA;
    private javax.swing.JButton guardar;
    private javax.swing.JButton guardarcomo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton redo;
    private javax.swing.JButton resaltar;
    private javax.swing.JButton undo;
    // End of variables declaration//GEN-END:variables
}
